# Generated by Django 4.2.11 on 2024-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_evento', models.DateField()),
                ('nivel_gas', models.IntegerField()),
                ('salas', models.JSONField()),
            ],
        ),
    ]
